x-common-variables: &common-variables
  networks:
    - backend_network

x-common-healthcheck: &common-healthcheck
  interval: 10s
  timeout: 10s
  retries: 5

x-common-env: &common-env
  env_file:
    - .env

services:

  redis:
    image: redis:7.4.1
    container_name: redis
    volumes:
      - redis-data:/data
    healthcheck:
      <<: *common-healthcheck
      test: [ "CMD", "redis-cli", "ping" ]
    <<: [ *common-variables, *common-env ]

  nginx:
    image: nginx:1.27.4
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./server/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./client/dist:/client/dist:ro
    depends_on:
      chat_service:
        condition: service_started
    <<: *common-variables

  chat_service:
    build:
      context: ./server/chat_service
      dockerfile: Dockerfile
    image: chat_service
    container_name: chat_service
    volumes:
      - chat_service_logs:/opt/chat_service/logs
    command: [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000" ]
    env_file:
      - server/chat_service/.env
    depends_on:
      redis:
        condition: service_healthy
    <<: [ *common-variables ]

volumes:
  redis-data:
  chat_service_logs:

networks:
  backend_network:
    driver: bridge